[package]
name = "life-criteria-py"
version = "0.1.0"
edition.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
life-criteria-core = { path = "../life-criteria-core" }
pyo3.workspace = true
serde_json.workspace = true
rand.workspace = true
rand_chacha.workspace = true
