[package]
name = "digital-life-py"
version = "0.1.0"
edition.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
digital-life-core = { path = "../digital-life-core" }
pyo3.workspace = true
serde_json.workspace = true
